name: Build

on:
  push:
    branches: [ main ]   # runs every time you push to main
  workflow_dispatch:      # also adds a manual "Run" button in GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x build.sh

      - name: Run build
        run: ./build.sh
